name: spunto-env
channels:
  - conda-forge
dependencies:
  - cmake>=3.20
  - gxx
  - gcc
  - sdl2<3
  - sdl2_ttf
  - glew
  - libpng
  - libpng-devel
  - pkg-config
  - zlib
  - libopengl-devel
  - libopengl
  - libgl-devel
  - libglx-devel
  - jinja2
  - fontconfig
