name: spunto-env
channels:
  - conda-forge
dependencies:
  - cmake>=3.20
  - gxx
  - gcc
  - sdl2
  - sdl2_ttf
  - glew
  - libpng
  - zlib
  - libopengl-devel
  - libopengl
  - libgl-devel
  - jinja2
