name: Build AppImage

on:
  push:
    branches: [ SDL_OGL45 ]
  pull_request:
    branches: [ SDL_OGL45  ]
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y \
            cmake g++ make \
            libglew-dev libsdl2-dev libsdl2-ttf-dev \
            libpng-dev libgl1-mesa-dev libglu1-mesa-dev \
            wget

      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_APPIMAGE=ON

      - name: Build AppImage
        run: |
          cd build
          make -j appimage

      - name: Make sure AppImage is there
        run: ls -l build/spunto-x86_64.AppImage
        
      - name: Run AppImage
        run: |
          chmod +x build/spunto-x86_64.AppImage
          ./build/spunto-x86_64.AppImage -h

      - name: Upload AppImage artifact (CI use only)
        uses: actions/upload-artifact@v3
        with:
          name: spunto-AppImage
          path: build/*.AppImage

      - name: Upload AppImage to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
